[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "graphcrawl_ai"
version = "0.1.0"
description = "An AI powered web scraper."
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT"}

dependencies = [
    "fastapi[standard]",
    "uvicorn",
    "httpx",
    "beautifulsoup4",
    "google-genai",
    "python-dotenv",
    "pydantic"
]

[tool.setuptools]
packages = ["graphcrawl_ai"]