from pydantic import BaseModel, Field
from typing import Literal, Optional


# =====================================================================================================================
# Response models for parsed content genetated by GraphCrawl internally from user request "crawl_url()"
# =====================================================================================================================
class HtmlParsedContent(BaseModel):
    """
    Represents structured content extracted from raw HTML.

    This model is produced by the internal HTML parsing stage. It acts as the 
    sanitized intermediate payload containing clean textual data and page metadata 
    before LLM processing.

    Attributes:
        title: Title of the HTML page.
        content: Extracted clean text from HTML.
    """
    title: str = Field(..., description="The extracted title of the source HTML page.")
    content: str = Field(..., description="The cleaned, raw text content parsed from the HTML body.")

# =======================================================================================================================




# ================================================================================================================
# Reponse models for response generated by LLM from user request from "crawl_url()" 
# ================================================================================================================
class UrlPromptResponseByLLM(BaseModel):
    """
    Represents the LLM response for a custom user-defined prompt extraction.

    This model captures the flexible, unstructured outcome generated when a user 
    provides their own specific natural language extraction instructions.

    Attributes:
        status: The execution state of the LLM extraction process.
        response: A dynamic dictionary containing the custom structured fields requested by the user.
    """
    status: Literal["success", "failure"] = Field(..., description="The final execution status of the extraction process.")
    response: dict = Field(..., description="The dynamic structured key-value pairs generated from the custom prompt.")


class UrlSummaryResponseByLLM(BaseModel):
    """
    Represents the LLM response for the 'SUMMARY' quick option mode.

    This model captures high-level overview details, synthesizing the main 
    points and core highlights of the processed web page.

    Attributes:
        status: The execution state of the LLM extraction process.
        summary: A comprehensive textual summary of the page content.
        key_takeaways: A list of bulleted, critical highlights extracted from the content.
    """
    status: Literal["success", "failure"] = Field(..., description="The final execution status of the extraction process.")
    summary: str = Field(..., description="A high-level text summary of the parsed webpage content.")
    key_takeaways: list = Field(..., description="A bulleted list of the most important insights extracted from the text.")


class UrlContactsResponseByLLM(BaseModel):
    """
    Represents the LLM response for the 'CONTACTS' quick option mode.

    This model isolates corporate and personal communication information found 
    on the processed web page.

    Attributes:
        status: The execution state of the LLM extraction process.
        contact_info: A dictionary containing identified contact details (e.g., emails, phone numbers, addresses).
    """
    status: Literal["success", "failure"] = Field(..., description="The final execution status of the extraction process.")
    contact_info: dict = Field(..., description="A dictionary storing isolated contact channels like emails, phone numbers, and physical addresses.")


class UrlProductsResponseByLLM(BaseModel):
    """
    Represents the LLM response for the 'PRODUCTS' quick option mode.

    This model is tailored for e-commerce or catalog pages, mapping out structured 
    inventories, merchandise items, or services listed on the page.

    Attributes:
        status: The execution state of the LLM extraction process.
        products_found: A boolean flag indicating if any relevant products were identified.
        products: A list of objects detailing each discovered product (e.g., name, price, description).
        message: An optional status or context message from the extraction engine.
    """
    status: Literal["success", "failure"] = Field(..., description="The final execution status of the extraction process.")
    products_found: bool = Field(..., description="Boolean flag indicating whether any valid product entries were discovered.")
    products: list[dict] = Field(..., description="A collection of items representing the catalog or products found on the page.")
    message: Optional[str] = Field(None, description="Optional informational or error message regarding the product discovery.")


class UrlAutoResponseByLLM(BaseModel):
    """
    Represents the LLM response for the fallback or intelligent 'AUTO' quick option mode.

    This model is applied when the system autonomously determines the optimal 
    extraction structure based on the intrinsic nature of the fetched content.

    Attributes:
        status: The execution state of the LLM extraction process.
        response: A dynamically inferred list of objects representing the core entities found on the page.
        message: Descriptive metadata or reasoning from the LLM explaining the auto-classification strategy.
    """
    status: Literal["success", "failure"] = Field(..., description="The final execution status of the extraction process.")
    response: list[dict] = Field(..., description="The dynamically generated schema containing elements extracted during autonomous classification.")
    message: str = Field(..., description="A descriptive log message explaining how the content structure was handled or inferred.")

# =======================================================================================================================