import os, json
from dotenv import load_dotenv
from google import genai
from graphcrawl_ai.models.request_models.crawl_url_models.request_url_internal import ExtractionRequestToLLM

load_dotenv()

llm_api = str(os.getenv("GEMINI_API"))

def get_response_gemini(request: ExtractionRequestToLLM) -> dict:
    """Submit the processed internal payload to Gemini and retrieve structured JSON data.

    This function serializes the internal request metadata (parsed content and resolved prompt),
    dispatches it to the Google GenAI API using a lightweight inference model, and enforces 
    a strict JSON response MIME type structure. The resulting raw text block is then sanitized 
    and deserialized back into a Python dictionary.

    Args:
        request: An ExtractionRequestToLLM object containing the sanitized webpage content 
            and structural prompt instructions.

    Returns:
        A dictionary containing the structured extraction schema generated by the LLM.

    Note:
        The function relies on a globally defined `GEMINI_API` key loaded from environmental variables
        and sets `response_mime_type` to guarantee predictable structure formatting.
    """
    client = genai.Client(api_key=llm_api)

    response = client.models.generate_content(
        model="gemini-3.1-flash-lite",
        contents=f"{request.model_dump()}",
        config={
            'response_mime_type': 'application/json'
        }
    )
    print(response.text)

    text_response = response.text.encode()
    json_response = json.loads(text_response)

    return json_response